export const entities = [
  {
    key: 'clientes',
    label: 'Clientes',
    singularLabel: 'Cliente',
    routeBase: '/clientes',
    apiBasePath: '/cliente',
    idField: 'idCliente',
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
    fields: [
      { name: 'razaoSocial', label: 'Razao Social', type: 'text', required: true },
      { name: 'nomeFantasia', label: 'Nome Fantasia', type: 'text', required: false },
      { name: 'cnpj', label: 'CNPJ', type: 'text', required: true },
      { name: 'telefone', label: 'Telefone', type: 'text', required: false },
      { name: 'email', label: 'E-mail', type: 'email', required: false },
    ],
  },
  {
    key: 'contatos',
    label: 'Contatos',
    singularLabel: 'Contato',
    routeBase: '/contatos',
    apiBasePath: '/contatos',
    idField: 'idContato',
    allowCreate: true,
    allowEdit: true,
    allowDelete: false,
    fields: [
      { name: 'nome', label: 'Nome', type: 'text', required: true },
      { name: 'email', label: 'E-mail', type: 'email', required: false },
      { name: 'telefone', label: 'Telefone', type: 'text', required: false },
      { name: 'idCliente', label: 'Cliente', type: 'select', valueType: 'number', required: false },
      { name: 'idDistribuidor', label: 'Distribuidor', type: 'select', valueType: 'number', required: false },
    ],
  },
  {
    key: 'distribuidores',
    label: 'Distribuidores',
    singularLabel: 'Distribuidor',
    routeBase: '/distribuidores',
    apiBasePath: '/distribuidor',
    idField: 'idDistribuidor',
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
    fields: [
      { name: 'razaoSocial', label: 'Razao Social', type: 'text', required: true },
      { name: 'nomeFantasia', label: 'Nome Fantasia', type: 'text', required: false },
      { name: 'cnpj', label: 'CNPJ', type: 'text', required: true },
      { name: 'telefone', label: 'Telefone', type: 'text', required: false },
      { name: 'email', label: 'E-mail', type: 'email', required: false },
    ],
  },
  {
    key: 'usuarios',
    label: 'Usuarios',
    singularLabel: 'Usuario',
    routeBase: '/usuarios',
    apiBasePath: '/usuario',
    idField: 'idUsuario',
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
    fields: [
      { name: 'nome', label: 'Nome', type: 'text', required: true },
      { name: 'email', label: 'E-mail', type: 'email', required: true },
      { name: 'senha', label: 'Senha', type: 'password', required: true },
      { name: 'telefone', label: 'Telefone', type: 'text', required: true },
    ],
  },
  {
    key: 'produtos',
    label: 'Produtos',
    singularLabel: 'Produto',
    routeBase: '/produtos',
    apiBasePath: '/produto',
    idField: 'idProduto',
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
    fields: [
      { name: 'nome', label: 'Nome', type: 'text', required: true },
      { name: 'descricao', label: 'Descricao', type: 'text', required: true },
    ],
  },
  {
    key: 'pedidos',
    label: 'Pedidos',
    singularLabel: 'Pedido',
    routeBase: '/pedidos',
    apiBasePath: '/pedidos',
    idField: 'idPedido',
    allowCreate: true,
    allowEdit: true,
    allowDelete: true,
    fields: [
      { name: 'dataPedido', label: 'Data do Pedido', type: 'date', required: true },
      { name: 'numeroNotaDistribuidor', label: 'Nota Distribuidor', type: 'number', required: false },
      { name: 'valorTotalRevenda', label: 'Valor Revenda', type: 'number', required: true },
      { name: 'valorTotalFaturamento', label: 'Valor Faturamento', type: 'number', required: true },
      { name: 'statusPedido', label: 'Status', type: 'text', required: true },
      { name: 'frete', label: 'Frete', type: 'select', valueType: 'boolean', required: true },
      { name: 'transportadora', label: 'Transportadora', type: 'text', required: false },
      { name: 'observacoes', label: 'Observacoes', type: 'text', required: false },
      { name: 'fkCliente', label: 'Cliente', type: 'select', valueType: 'number', required: true },
      {
        name: 'fkDistribuidor',
        label: 'Distribuidor',
        type: 'select',
        valueType: 'number',
        required: true,
      },
      {
        name: 'itens',
        label: 'Itens (JSON)',
        type: 'textarea',
        valueType: 'json',
        required: true,
        helpText:
          'Use o formato [{"fkProduto": 1, "quantidade": 2, "valorUnitario": 39.9}] para criar pedidos.',
      },
    ],
  },
  {
    key: 'itens-pedido',
    label: 'Itens do Pedido',
    singularLabel: 'Item do Pedido',
    routeBase: '/itens-pedido',
    apiBasePath: '/item_pedido',
    idField: 'idItemPedido',
    allowCreate: false,
    allowEdit: false,
    allowDelete: true,
    fields: [
      { name: 'idItemPedido', label: 'ID', type: 'number', required: false },
      { name: 'pedido.idPedido', label: 'Pedido', type: 'number', required: false },
      { name: 'produto.nome', label: 'Produto', type: 'text', required: false },
      { name: 'quantidade', label: 'Quantidade', type: 'number', required: false },
      { name: 'valorUnitario', label: 'Valor Unitario', type: 'number', required: false },
    ],
  },
]

export const entityMap = entities.reduce((acc, entity) => {
  acc[entity.key] = entity
  return acc
}, {})
